#
# Module manifest for module 'M365LicenseManager'
#
# Generated by: Rahul Namdev
# Generated on: 29-06-2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'M365LicenseManager.psm1'

# Version number of this module.
ModuleVersion = '0.6.0'

# Supported PowerShell editions.
CompatiblePSEditions = @(
    'Core'
)

# ID used to uniquely identify this module.
GUID = '8767107d-52ca-437f-8cee-fb5eb26e4c9c'

# Author of this module.
Author = 'Rahul Namdev'

# Company or vendor of this module.
CompanyName = 'Independent'

# Copyright statement for this module.
Copyright = '(c) Rahul Namdev. All rights reserved.'

# Description of the functionality provided by this module.
Description = 'PowerShell module for managing Microsoft 365 licenses using Microsoft Graph.'

# Minimum version of the PowerShell engine required by this module.
PowerShellVersion = '7.2'

# Functions to export from this module.
FunctionsToExport = @(
    'Connect-M365License',
    'Test-M365Prerequisites',
    'Get-M365LicenseInventory',
    'Get-M365UserLicense',
    'Set-M365UserLicense',
    'Remove-M365UserLicense',
    'Copy-M365UserLicense',
    'Compare-M365UserLicense'
    'New-M365LicenseReport'
)

# Cmdlets to export from this module.
CmdletsToExport = @()

# Variables to export from this module.
VariablesToExport = @()

# Aliases to export from this module.
AliasesToExport = @()

# Private data.
PrivateData = @{

    PSData = @{

        Tags = @(
            'Microsoft365',
            'MicrosoftGraph',
            'Microsoft365License',
            'EntraID',
            'PowerShell',
            'Office365',
            'GraphAPI',
            'Administration'
        )

        ProjectUri = 'https://github.com/Rahulnamdev365/M365LicenseManager'

        ReleaseNotes = @'
v0.3.0

Initial public release.

Features
- Microsoft Graph connectivity
- User license inventory
- Tenant license inventory
- License assignment
- License removal
- License copy
- License comparison
- Comment-based help
'@

    }

}

}