function ConvertTo-LicenseExcel {

    <#
    .SYNOPSIS
        Exports a Microsoft 365 License Report to Excel.

    .DESCRIPTION
        Creates a formatted Excel workbook containing report statistics,
        license inventory, users, and unlicensed users.

    .PARAMETER Report
        Report object generated by New-M365LicenseReport.

    .PARAMETER OutputPath
        Folder where the Excel workbook will be saved.

    .OUTPUTS
        System.IO.FileInfo

    .NOTES
        Author  : Rahul Namdev
        Version : 0.7.0
    #>

    [CmdletBinding()]
    param(

        [Parameter(Mandatory)]
        [psobject]$Report,

        [Parameter(Mandatory)]
        [string]$OutputPath

    )

    # ============================================================
    # Verify ImportExcel Module
    # ============================================================

    if (-not (Get-Module -ListAvailable -Name ImportExcel)) {

        throw @"
The ImportExcel module is required.

Install it using:

Install-Module ImportExcel -Scope CurrentUser
"@

    }

    Import-Module ImportExcel -Force

    # ============================================================
    # Ensure Output Folder Exists
    # ============================================================

    if (-not (Test-Path $OutputPath)) {

        New-Item `
            -ItemType Directory `
            -Path $OutputPath `
            -Force | Out-Null

    }

    # ============================================================
    # Workbook
    # ============================================================

    $ExcelFile = Join-Path `
        -Path $OutputPath `
        -ChildPath "LicenseReport.xlsx"

    if (Test-Path $ExcelFile) {

        Remove-Item $ExcelFile -Force

    }

    # ============================================================
    # Executive Summary
    # ============================================================

    $Summary = @(
        [PSCustomObject]@{
            Metric = "Core Licenses"
            Value  = $Report.Statistics.TotalPurchased
        }

        [PSCustomObject]@{
            Metric = "Teams & Communication"
            Value  = $Report.Statistics.CommunicationPurchased
        }

        [PSCustomObject]@{
            Metric = "Add-ons"
            Value  = $Report.Statistics.AddOnPurchased
        }

        [PSCustomObject]@{
            Metric = "Trial Licenses"
            Value  = $Report.Statistics.TrialPurchased
        }

        [PSCustomObject]@{
            Metric = "Free Licenses"
            Value  = $Report.Statistics.FreePurchased
        }

        [PSCustomObject]@{
            Metric = "License Utilization"
            Value  = "$($Report.Statistics.LicenseUtilizationPercent)%"
        }
    )

    $Summary |
        Export-Excel `
            -Path $ExcelFile `
            -WorksheetName "Executive Summary" `
            -TableName ExecutiveSummary `
            -AutoSize `
            -BoldTopRow `
            -FreezeTopRow

    # ============================================================
    # Statistics
    # ============================================================

    $Report.Statistics.PSObject.Properties |
        Select-Object Name, Value |
        Export-Excel `
            -Path $ExcelFile `
            -WorksheetName "Statistics" `
            -TableName Statistics `
            -AutoSize `
            -BoldTopRow `
            -FreezeTopRow

    # ============================================================
    # License Inventory
    # ============================================================

    $Report.Summary |
        Export-Excel `
            -Path $ExcelFile `
            -WorksheetName "License Inventory" `
            -TableName Inventory `
            -AutoSize `
            -BoldTopRow `
            -FreezeTopRow

    # ============================================================
    # Users
    # ============================================================

    $Report.Users |
        Export-Excel `
            -Path $ExcelFile `
            -WorksheetName "Users" `
            -TableName Users `
            -AutoSize `
            -BoldTopRow `
            -FreezeTopRow

    # ============================================================
    # Unlicensed Users
    # ============================================================

    $Report.UnlicensedUsers |
        Export-Excel `
            -Path $ExcelFile `
            -WorksheetName "Unlicensed Users" `
            -TableName UnlicensedUsers `
            -AutoSize `
            -BoldTopRow `
            -FreezeTopRow

    # ============================================================
    # Return Workbook
    # ============================================================

    return Get-Item $ExcelFile

}